# -*- coding: utf-8 -*-
"""insurance_cost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3r2mygXwLJRQ9-osTwuVj2u636ZBjUB
"""

def calculate_insurance_cost(age,sex,bmi,num_of_children,smoker,name):
  estimated_cost=250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500
  print("The estimated insurance cost for "+name+ " is "+str(estimated_cost)+ "dollars.")
  return estimated_cost


maria_insurance_cost=calculate_insurance_cost(28,0,26.2,3,10,name="Maria") 
Omar_insurance_cost=calculate_insurance_cost(35,1,22.2,0,1,name="Omar")

# Function to estimate insurance cost:
def estimate_insurance_cost(name, age, sex, bmi, num_of_children, smoker):
  estimated_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500
  print(name + "'s Estimated Insurance Cost: " + str(estimated_cost) + " dollars.")
  return estimated_cost

# Estimate Maria's insurance cost
maria_insurance_cost = estimate_insurance_cost(name = "Maria", age = 31, sex = 0, bmi = 23.1, num_of_children = 1, smoker = 0)

# Estimate Rohan's insurance cost
rohan_insurance_cost = estimate_insurance_cost(name = 
"Rohan", age = 25, sex = 1, bmi = 28.5, num_of_children = 3, smoker = 0)

# Estimate Valentina's insurance cost
valentina_insurance_cost = estimate_insurance_cost(name = "Valentina", age = 53, sex = 0, bmi = 31.4, num_of_children = 0, smoker = 1)

# Add your code here

names=["Maria","Rohan","Valentina"]
insurance_costs=[4150.0,5320.0,35210.0]
insurance_data=list(zip(names,insurance_costs))
estimated_insurance_data=[]
estimated_insurance_data.append(("Maria", maria_insurance_cost))
estimated_insurance_data.append(("Rohan", rohan_insurance_cost))
estimated_insurance_data.append(("Valentina", valentina_insurance_cost))
print(estimated_insurance_data)
print("Here is the actual insurance cost data: " + str(insurance_data))
print("Here is the estimated insurance cost data: " + str(estimated_insurance_data))